export default {
  grid: {
    container: '130rem',
    gutter: '3.2rem',
  },
  border: {
    littleRadius: '5px',
    radius: '8px',
  },
  zIndex: {
    mobileStepper: 1000,
    speedDial: 1050,
    appBar: 1100,
    drawer: 1200,
    modal: 1300,
    modal2: 1350,
    snackbar: 1400,
    tooltip: 1500,
  },
  font: {
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xxsmall: '1rem',
      xsmall: '1.2rem',
      small: '1.5rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.8rem',
    },
    family:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    largeText: {
      fontFamily: 'Poppins',
      fontSize: '35px',
      letterSpacing: '0px',
    },
    meduimText: {
      fontFamily: 'Poppins',
      fontSize: '22px',
      letterSpacing: '0px',
    },
    smallText: {
      fontFamily: 'Poppins',
      fontSize: '18px',
      letterSpacing: '0px',
    },
    text: {
      fontFamily: 'Poppins',
      fontSize: '15px',
      letterSpacing: '0px',
    },
  },
  colors: {
    primary: '#041B4D',
    secondary: '#3075DD',
    green: '#52B158',
    backgroundAll: '#E5E5E5',
    red: '#C74163',
    default: '#D5D5D5',
    white: '#FAFAFA',
    lightWhite: '#FFFFFF',
    black: '#030517',
    gray: '#8F8F8F',
    danger: '#DD665F',
  },
  spacings: {
    xxsmall: '8px',
    xsmall: '16px',
    small: '24px',
    medium: '32px',
    large: '40px',
    xlarge: '48px',
    xxlarge: '56px',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
};
